Module3 task1
echebotarev/24321-code-and-magick pull request #3
Opened 2018-10-19 09:18 UTC by yakosha

2018-10-19 09:19 UTC, yakosha commented
не могу понять как написать функцию для рандомной отрисовки каждого волшебника

2018-10-19 16:49 UTC, echebotarev requested changes
Убери пожалуйста весь закомментированный код

2018-10-19 16:49 UTC, echebotarev commented on js/setup.js
> +for (var i = 0; i < 4; i++) {
А почему ты используешь `i < 4`, а не `i < arr.length`?

2018-10-19 16:49 UTC, echebotarev commented on js/setup.js
> +for (var i = 0; i < 4; i++) {
Ведь мы отрисовываем сгенерированных волшебников

2018-10-19 16:49 UTC, echebotarev commented on js/setup.js
> +  wizardElement.querySelector('.wizard-eyes').style.fill =  eyesColor;
Наверно в присваивании имен волшебников и цветов их глаз с плащами тебе пригодится массив с волшебниками

2018-10-29 17:56 UTC, closed without merging

2018-10-30 09:47 UTC, yakosha commented
оптимизация