обработка событий
echebotarev/24321-code-and-magick pull request #5
Opened 2018-11-21 21:42 UTC by yakosha

2018-11-22 13:57 UTC, echebotarev requested changes
1. Давай договоримся, что я не буду проверять задание пока отступы, пробелы и переносы строк не будут такими какими должны. Поправь пожалуйста.
2. Вынеси обработчики событий в отдельные ф-ии. К примеру у тебя повторяется код поо открытию окна и его скрытию. Вынеси их в `showPopup` и `closePopup`
3. У тебя ошибка в консоли
4. Удали все console.log'и и не добавляй в репозиторий комментарии. 
В sourcetree можно выделять строки, которые ты хочешь закоммитить. Тем самым ты оставишь комментарии локально у себя и не будешь добавлять их в репозиторий.

2018-11-22 13:57 UTC, echebotarev commented on js/setup.js
> +    if (evt.keyCode === 27) {
Если фокус находится на форме ввода имени, то окно закрываться не должно.
Используй document.activeElement

2018-11-22 14:00 UTC, echebotarev requested changes

2018-11-22 14:00 UTC, echebotarev commented on js/setup.js
> +    ctx.fillStyle = 'hsl(240,' + Math.round(Math.random() * 100)  +'%,'+Math.round(Math.random() * 100) +'% )'
– Инлайновым css-свойством  называется style="width: 100%; и тд"
– В задании тебе дан список цветов. Создай из него массив и выбирай цвет рандомно, как мы это уже делали.

2018-12-03 14:54 UTC, yakosha commented
итоговая работа

2018-12-08 01:52 UTC, echebotarev requested changes
1. document.activeElement доступен только для чтения и не является ф-ей. Почитай это https://developer.mozilla.org/ru/docs/Web/API/Document/activeElement
Из-за этой ошибки у тебя не выполняется пункт 1.2
Твоя задача: в ф-ии closePopup проверять чем является document.activeElement. Если инпутом с вводом имени, то попап закрывать нельзя
2. Не выполняется этот пункт:

> Для того, чтобы на сервер отправились правильные данные, при изменении параметров персонажа должно изменяться и значение соответствующего скрытого инпута.

2018-12-08 01:52 UTC, echebotarev commented on js/setup.js
> +    setup.classList.remove('hidden');
У тебя ведь ф-ия closePopup, используй ее

2018-12-08 01:52 UTC, echebotarev commented on js/setup.js
> +  var randomColor = COLORS[randomInteger(COLORS.length - 1)];
В этом и прочих местах не надо записывать значение в переменную, а после присваивать в wizzardCoat.style.fil, пиши сразу 
`wizzardCoat.style.fill = COLORS[randomInt]`

2018-12-14 01:58 UTC, echebotarev requested changes
У тебя не выполняется пункт 5:

> Для того, чтобы на сервер отправились правильные данные, при изменении параметров персонажа должно изменяться и значение соответствующего скрытого инпута.

2018-12-25 06:14 UTC, merged